### ISSUE TITLE
noob here: how use this

### ISSUE THREAD

**Issue by cocodrino** [skatardude10/dotfiles#1]
Hi man, I see your configuration in reddit and this looks crazy awesome, probably the best desktop configuration than I've seen so far, I'm trying to recreate this in my machine but it's not clear how achieve this:  I've used manjaro i3 and now I'm trying to install i3 from zero in other arch machine...I know how works with i3 but I'm not so much clear about how configure it (I know about the config file and basic parameters)

I suppose than I need install yabar and other tools before place the config files but I'm not clear about what packages I need before, can you give me a brief guide about how configure the i3?..thank you!!!

**Comment by skatardude10** [comment]
First of all, thanks.  The visual style has changed a lot since I have made any posts about it on Reddit though, so if there is a specific look you are going for you will probably have to dig back in the repositories history. 

Can you link me the Reddit post you are referring to? That way, I might be able to help you find the exact scripts in the history that you would want to reference to do something similar.

As for packages, just guessing based off my history, you will probably want: 

- ttf-font-awesome (for icons)
- rofi (for menus)
- yabar

I like to reference scripts in my scripts folder for yabar buttons and stuff... a lot of them might not work out of the box unless the repo is cloned in $HOME or ~/, because most of my buttons and stuff reference ~/dotfiles/scripts/script-whatever.sh, so i'd recommend just copying the scripts you need, place them where you want and modify the config files and script paths as necessary.

**Comment by cocodrino** [comment]
Hi man...yes the link is https://www.reddit.com/r/unixporn/comments/4os77z/i3_happy_times_switched_to_yabar/

yes, I was checking the code yesterday and I think than moving the script folder to ~/ and copy the yabar, i3 and rofi code in their config files is enough, there are other configurations like clerk, lightdm and ncmpcpp than doesnt seems to necesary right now..maybe I'm wrong...

man your desktop is the best linux desktop than I've seen in my entire life, looks gorgeous and I think than is have the linux essence, instead of replicating the macOS/windows look, if some distro take inspiration in it, would be great...I think than except the font it is perfect...thanks!!!
